### ISSUE TITLE
from osv import osv, fields ImportError: No module named osv

### ISSUE THREAD

**Issue by diezcode** [OCA/connector-sage#13]
In odoo8 this module is not working:
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 439, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 443, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1316, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom_addons/exportsage50/**init**.py", line 22, in <module>
    import wizard
  File "/opt/odoo/custom_addons/exportsage50/wizard/**init**.py", line 22, in <module>
    import exportsage50
  File "/opt/odoo/custom_addons/exportsage50/wizard/exportsage50.py", line 22, in <module>
    from osv import osv, fields
ImportError: No module named osv

I think the error is because it should be "from openerp import osv, fields"
Any info?

**Comment by diezcode** [comment]
after I changed the import:
in module : from osv import fields, osv
changed to:
from openerp.osv import fields, osv

I get a new error:

ImportError: No module named web

**Comment by diezcode** [comment]
@sbidoul Can someone fix this module? for odoo version 8
